version: '3.8'

services:
  client:
    build:
      context: .
      target: client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build:
      context: .
      target: server
    healthcheck:
       test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001/api/health"]
       interval: 30s
       timeout: 10s
       retries: 3
       start_period: 20s
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    deploy:
       resources:
         limits:
           memory: 512M
    restart: unless-stopped