version: '3.8'

services:
  client:
    build:
      context: .
      target: client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - NODE_ENV=production

  server:
    build:
      context: .
      target: server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - PORT=3001
