version: '3.8'

services:
  client:
    build:
      context: .
      target: client
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    build:
      context: .
      target: server
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production