version: '3.8'

services:
  client:
    image: ghcr.io/draco1js/hackops-submission/client:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    depends_on:
      - server

  server:
    image: ghcr.io/draco1js/hackops-submission/server:latest
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production