services:
  - type: web
    name: todo-app-client
    env: static
    buildCommand: pnpm install && pnpm --filter client build
    staticPublishPath: ./packages/client/dist
    envVars:
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: todo-app-server
    env: node
    buildCommand: pnpm install && pnpm --filter server build
    startCommand: node packages/server/dist/index.js
    envVars:
      - key: NODE_ENV
        value: production